# Default application configuration that all configurations inherit from.
#

linters:

  Indentation:
    enabled: true
    character: space
    width: 2

  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: false

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: false
    present: true

  HexLength:
    enabled: true
    style: long # or 'short'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    allow_leading_underscore: false
    # placeholder_convention: /[A-Z]|-{3}|_{3}|[^_]_[^_]/ # or hyphenated_lowercase #, or a regex pattern

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    order:
    - display
    - position
    - top
    - right
    - bottom
    - left

    - float
    - clear

    - visibility
    - opacity
    - z-index

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - outline

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - background
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size
    - cursor

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - overflow

    - list-style
    - caption-side

    - table-layout
    - border-collapse
    - border-spacing
    - empty-cells

    - vertical-align

    - text-align
    - text-indent
    - text-transform
    - text-decoration

    - line-height
    - word-spacing
    - letter-spacing
    - white-space
    - color

    - font
    - font-family
    - font-size
    - font-weight

    - content
    - quotes

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4

  SelectorFormat:
    enabled: true
    convention: 'hyphenated_BEM'

  Shorthand:
    enabled: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes #or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

Compass::*:
  enabled: false
